=== haidaraM/tp_xml/petit_prince_3IF.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT texte (en-tete, corps)>
<!ELEMENT en-tete (titre, auteur, couverture, info_traitements, lien+)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT lien (#PCDATA)>
<!ATTLIST lien
          langue CDATA #REQUIRED>
<!ELEMENT couverture EMPTY>
<!ATTLIST couverture
          chemin CDATA #REQUIRED>
<!ELEMENT info_traitements (but, mise_en_forme_par, email, date)>
<!ELEMENT but (#PCDATA)>
<!ELEMENT mise_en_forme_par (unCreateur+, NoBinome)>
<!ELEMENT unCreateur (#PCDATA)>
<!ELEMENT NoBinome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT corps (paragraphe+, image, paragraphe+)>
<!ELEMENT paragraphe (phrase+)>
<!ATTLIST paragraphe
          type CDATA #REQUIRED>
<!ELEMENT phrase (#PCDATA)>
<!ATTLIST phrase
          locuteur CDATA #REQUIRED
          modalite CDATA #REQUIRED
          langue CDATA #REQUIRED>
<!ELEMENT image EMPTY>
<!ATTLIST image
          chemin CDATA #REQUIRED>

=== haidaraM/tp_xml/petit_prince_3IF.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="petit_prince_boostrap.xsl"?>
<!DOCTYPE texte SYSTEM "petit_prince_3IF.dtd">
<texte>
  <en-tete>
    <titre>LePetitPrince</titre>
    <auteur>Antoine de Saint-Exupéry</auteur>
    <couverture chemin="images/prince.png"/>
    <info_traitements>
      <but>Traitement d'un texte franco/hongrois avec XPath / XSLT / XQuery</but>
      <mise_en_forme_par>
        <unCreateur> Mohamed Haidara</unCreateur>
        <unCreateur>Yoam Hazot</unCreateur>
        <NoBinome>B3446</NoBinome>
      </mise_en_forme_par>
      <email>yoam.hazot@insa-lyon.fr</email>
      <date>10/04/2015</date>
    </info_traitements>
    <lien langue="francais">http://wikilivres.info/wiki/Le_Petit_Prince</lien>
    <lien langue="hongrois">http://mek.oszk.hu/00300/00384/00384.pdf</lien>
  </en-tete>
  <corps>
    <paragraphe type="narration">
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">J'ai ainsi vécu seul, sans personne avec qui parler véritablement, jusqu'à une panne dans le désert du Sahara, il y a six ans. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Quelque chose s'était cassé dans mon moteur, et comme je n'avais avec moi ni mécanicien, ni passagers, je me préparai à essayer de réussir, tout seul, une réparation difficile. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">C'était pour moi une question de vie ou de mort. J'avais à peine de l'eau à boire pour huit jours. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Így éltem magányosan, anélkül, hogy igazában bárkivel is szót érthettem volna, míg egyszer, hat esztendővel ezelőtt, kényszerleszállást nem kellett végeznem a Szaharában.  </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Valami eltörött a motoromban. És mivel se gépészem nem volt, se utasom, magamnak kellett nekilátnom, hogy zöld ágra vergődjem valahogyan, és kijavítsam a súlyos hibát.</phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Élet és halál kérdése volt ez számomra.</phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Alig egy hétre való ivóvizem volt.  </phrase>
    </paragraphe>
    <paragraphe type="narration">
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Le premier soir je me suis donc endormi sur le sable à mille milles de toute terre habitée. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">J'étais bien plus isolé qu'un naufragé sur un rideau au milieu de l'océan. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Alors vous imaginez ma surprise, au levé du jour, quand une drôle de petite voix m'a réveillé. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Elle disait: </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Ott dőltem álomra az első este a homokon, ezermérföldnyire minden lakott helytől.</phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Elhagyatottabb voltam, mint tutaján a hajótörött az óceán közepén.</phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Elképzelhető hát, mennyire meglepődtem, amikor hajnalban egy fura kis hang ébresztett föl. Azt mondta: </phrase>
    </paragraphe>
    <paragraphe type="dialogue">
      <phrase locuteur="LePetitPrince" modalite="declarative" langue="francais">S'il vous plaît... dessine-moi un mouton! </phrase>
      <phrase locuteur="LePetitPrince" modalite="declarative" langue="hongrois">Légy szíves, rajzolj nekem egy bárányt! </phrase>
      <phrase locuteur="Narrateur" modalite="exclamative" langue="francais">Hein! </phrase>
      <phrase locuteur="Narrateur" modalite="exclamative" langue="hongrois">Micsoda?  </phrase>
      <phrase locuteur="LePetitPrince" modalite="declarative" langue="francais">Dessine-moi un mouton... </phrase>
      <phrase locuteur="LePetitPrince" modalite="declarative" langue="hongrois">Rajzolj nekem egy bárányt...  </phrase>
    </paragraphe>
    <paragraphe type="narration">
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">J'ai sauté sur mes pieds comme si j'avais été frappé par la foudre. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">J'ai bien frotté mes yeux. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">J'ai bien regardé. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Et j'ai vu un petit bonhomme tout à fait extraordinaire qui me considérait gravement. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Voilà le meilleur portrait que, plus tard, j'ai réussi à faire de lui. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Mais mon dessin,bien sùr, est beaucoup moins ravissant que le modèle. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Ce n'est pas de ma faute. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">J'avais été découragé dans ma carrière de peintre par les grandes personnes, à l'age de six ans, et je n'avais rien appris à dessiner, sauf les boas fermés et les boas ouverts. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Fölugrottam, mintha villám csapott volna le mellettem. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Megdörgöltem a szememet, aztán jól kimeresztettem.</phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">És egy apró emberkét láttam, egy teljességgel rendkívüli kis emberkét, amint komoly figyelemmel szemlél.</phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Itt a legjobb kép, amit később csinálnom sikerült róla. Csakhogy az én rajzom kétségkívül sokkal kevésbé elragadó, mint amilyen a mintája volt. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Igaz, nem az én hibámból. Mert ami festői pályafutásomat illeti, attól már hatesztendős koromban elvették a kedvemet a fölnőttek, így aztán nem is tanultam meg rajzolni, kivéve a csukott meg a nyitott óriáskígyókat.  </phrase>
    </paragraphe>
    <paragraphe type="narration">
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Je regardai donc cette apparition avec des yeux tout ronds d'étonnement. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">N'oubliez pas que je me trouvais à mille milles de toute région habitée. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Or mon petit bonhomme ne me semblait ni égaré, ni mort de fatigue, ni mort de faim, ni mort de soif, ni mort de peur. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Il n'avait en rien l'apparence d'un enfant perdu au milieu du désert, à mille milles de toute région habitée. Quand je réussis enfin de parler, je lui dis: </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Ámulattól kerek szemmel néztem hát a különös tüneményt. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Ne feledjük el: ezer mérföldre voltam minden lakott vidéktől. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Emberkémen pedig semmi jele nem volt annak, mintha eltévedt volna, vagy halálosan fáradt, halálosan éhes, halálosan szomjas lenne, esetleg halálosan félne. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Egyáltalán nem úgy festett, mint egy szerencsétlen gyerek, aki eltévedt a sivatagban, ezermérföldnyire minden lakott helytől. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois">Mikor végre szavamra leltem, azt kérdeztem tőle:  </phrase>
    </paragraphe>
    <paragraphe type="dialogue">
      <phrase locuteur="Narrateur" modalite="interrogative" langue="francais">Mais qu'est-ce que tu fais là? </phrase>
      <phrase locuteur="Narrateur" modalite="interrogative" langue="hongrois">De hát... hogy kerülsz te ide? </phrase>
    </paragraphe>
    <paragraphe type="narration">
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Et il me répéta alors, tout doucement, comme une chose très sérieuse: </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="hongrois"> Erre szelíden, és mintha valami nagyon komoly dolgot kérne, megismételte:  </phrase>
    </paragraphe>
    <paragraphe type="dialogue">
      <phrase locuteur="LePetitPrince" modalite="declarative" langue="francais">S'il vous plaît... dessine-moi un mouton... </phrase>
      <phrase locuteur="LePetitPrince" modalite="declarative" langue="hongrois">Légy szíves, rajzolj nekem egy bárányt...  </phrase>
    </paragraphe>
    <paragraphe type="narration">
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Quand le mystère est trop impressionnant, on n'ose pas désobéir. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Aussi absurde que cela me semblaît à mille milles de tous les endroits habités et en danger de mort, je sortis de ma poche une feuille de papier et un stylographe. </phrase>
      <phrase locuteur="Narrateur" modalite="declarative" langue="francais">Mais je me rappelai alors que j'avais surtout étudié la géographie, l'histoire, le calcul et la grammaire et je dis au petit bonhomme (avec un peu de mauvaise humeur) que je ne savais pas dessiner. </phrase>
